name: ktlint

on:
  pull_request:
    paths:
      - .github/workflows/ktlint.yml
      - '**.kt'
      - '**.kts'

jobs:
  ktlint:
    name: Run ktlint
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
